staff/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^login/$', views.login, name='login'),
	url(r'^logout/$', views.logout, name='logout'),
	url(r'^register/$', views.register, name='register'),
	url(r'^users/$', views.users, name='users'),
	url(r'^message/$', views.webmessage, name='webmessage'),
	url(r'^users/(?P<user_pk>[0-9]+)/$', views.user, name='user'),
	url(r'^users/(?P<user_pk>[0-9]+)/settings/$', views.usersettings, name='usersettings'),
	url(r'^users/(?P<user_pk>[0-9]+)/settings/profile/$', views.userprofileupdate, name='userprofileupdate'),
	url(r'^users/(?P<user_pk>[0-9]+)/settings/social/$', views.usersociallinks, name='usersociallinks'),
	url(r'^users/(?P<user_pk>[0-9]+)/settings/avatar/$', views.useravatar, name='useravatar'),
	url(r'^users/(?P<user_pk>[0-9]+)/settings/background/$', views.userbackground, name='userbackground'),
	url(r'^users/(?P<user_pk>[0-9]+)/settings/change_password$', views.user_change_password, name='user_change_password'),
	url(r'^teams/$', views.teams, name='teams'),
	url(r'^teams/(?P<team_pk>[0-9]+)/$', views.team, name='team'),
	url(r'^teams/(?P<team_pk>[0-9]+)/settings/$', views.teamsettings_general, name='teamsettings_general'),
	url(r'^teams/(?P<team_pk>[0-9]+)/settings/message$', views.teamsettings_message, name='teamsettings_message'),
	url(r'^teams/(?P<team_pk>[0-9]+)/settings/logo/$', views.teamsettings_logo, name='teamsettings_logo'),
	url(r'^teams/(?P<team_pk>[0-9]+)/settings/background/$', views.teamsettings_background, name='teamsettings_background'),
	url(r'^teams/(?P<team_pk>[0-9]+)/settings/description/$', views.teamsettings_description, name='teamsettings_description'),
	url(r'^teams/(?P<team_pk>[0-9]+)/settings/members/$', views.teamsettings_members, name='teamsettings_members'),
	url(r'^teams/(?P<team_pk>[0-9]+)/settings/members/add/$', views.teamsettings_members_add, name='teamsettings_members_add'),
	url(r'^teams/(?P<team_pk>[0-9]+)/settings/members/delete/$', views.teamsettings_members_delete, name='teamsettings_members_delete'),
	url(r'^teams/(?P<team_pk>[0-9]+)/settings/applications/$', views.teamsettings_applications, name='teamsettings_applications'),
	url(r'^teams/(?P<team_pk>[0-9]+)/settings/applications/accepted/$', views.teamsettings_accept_applications, name='teamsettings_accept_applications'),
	url(r'^teams/(?P<team_pk>[0-9]+)/settings/applications/needinfo/$', views.teamsettings_needinfo_applications, name='teamsettings_needinfo_applications'),
	url(r'^teams/(?P<team_pk>[0-9]+)/settings/applications/refuse/$', views.teamsettings_refuse_applications, name='teamsettings_refuse_applications'),
	url(r'^apply/$', views.apply, name='apply'),
	url(r'^apply/sent/$', views.applysent, name='applysent'),
	url(r'^apply/accept/$', views.useraccept, name='useraccept'),
	url(r'^apply/delete/$', views.applydelete, name='applydelete'),
	url(r'^contact/$', views.contact, name='contact'),
	## PASSWORD RESET
	url(r'^password_reset/$', auth_views.password_reset, {
		'template_name'			  : 'reset/password_reset_form.html',
		'subject_template_name'	  : 'email/password_reset_subject.txt',
		'html_email_template_name': 'email/password_reset_email.html',
		'from_email'			  : 'info@victory.genki.dk'
		}, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done,{'template_name': 'reset/password_reset_done.html'}, name='password_reset_done'),
	url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm,{'template_name': 'reset/password_reset_confirm.html'}, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete,{'template_name': 'reset/password_reset_complete.html'}, name='password_reset_complete'),
]

victory/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^', include('staff.urls')),
	url(r'^admin/', admin.site.urls),
]

staff/models.py
from django.db import models

from django.contrib.auth.models import User
from django.core.validators import RegexValidator, MinValueValidator, MaxValueValidator
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.

class Team(models.Model):
	name = models.CharField(max_length=50)
	logo = models.ImageField(upload_to='teams/avatars', default='static/img/userpreload.png')
	background = models.ImageField(upload_to='teams/backgrounds', default='static/img/userpreload.png')
	description = models.TextField(blank=True)
	people_needed = models.PositiveSmallIntegerField()
	members = models.ManyToManyField(User, through='TeamMembership')
	accepts_applications = models.BooleanField()

	@property
	def teamleaders_listable(self):
		leaders = self.members.filter(teammembership__leader=True)
		return ", ".join(l.extendeduser.nickname for l in leaders)

	@property
	def multiple_teamleaders(self):
		if len(self.members.filter(teammembership__leader=True)) > 1:
			return True
		else:
			return False

	def __str__(self):
		return self.name

class TeamMembership(models.Model):
	user = models.ForeignKey(User)
	team = models.ForeignKey(Team)
	leader = models.BooleanField(default=False)
	groupleader = models.BooleanField(default=False)

class DriversLicenceCategories(models.Model): # No plural
	category = models.CharField(max_length=3)

	def __str__(self):
		return self.category

class Language(models.Model):
	name = models.CharField(max_length=16)

	def __str__(self):
		return self.name

class TShirt(models.Model):
	description = models.CharField(max_length=32)

class Sock(models.Model):
	description = models.CharField(max_length=32)

class ExtendedUser(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	nickname = models.CharField(max_length=20)
	birthdate = models.DateField(null=True, blank=True)
	postal_code = models.CharField(max_length=10)
	phone_number_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+4570131415'. Up to 15 digits allowed.")
	phone_number = models.CharField(max_length=16, validators=[phone_number_regex], blank=True)
	phone_number_show = models.BooleanField(default=False)
	emergency_number = models.CharField(max_length=16, validators=[phone_number_regex], blank=True)
	drivers_licence = models.ManyToManyField(DriversLicenceCategories, blank=True)
	avatar = models.ImageField(upload_to='users/avatars', default='static/img/userpreload.png')
	background = models.ImageField(upload_to='users/backgrounds', default='static/img/userpreload.png')
	team = models.ForeignKey(Team, null=True, blank=True)
	languages = models.ManyToManyField(Language, blank=True)
	tshirt = models.ForeignKey(TShirt, null=True, blank=True)
	sock = models.ForeignKey(Sock, null=True, blank=True)
	facebook_link = models.URLField(max_length=200, blank=True, null=True)
	twitter_link = models.URLField(max_length=200, blank=True, null=True)
	soundcloud_link = models.URLField(max_length=200, blank=True, null=True)
	youtube_link = models.URLField(max_length=200, blank=True, null=True)
	child_record = models.DateField(null=True, blank=True)
	special_considerations = models.TextField(blank=True)

@receiver(post_save, sender=User)
def update_user_extendeduser(sender, instance, created, **kwargs):
    if created:
        ExtendedUser.objects.create(user=instance)
    instance.extendeduser.save()

class Article(models.Model):
	author = models.ForeignKey(User)
	title = models.CharField(max_length=64)
	created = models.DateTimeField(null=True)
	body = models.TextField()

	def __str__(self):
		return self.title

class Alert(models.Model):
	title = models.CharField(max_length=32)
	body = models.TextField(blank=True)
	start = models.DateTimeField()
	end = models.DateTimeField()

class UnauthenticatedSession(models.Model):
	user = models.ForeignKey(User)
	token = models.CharField(max_length=36)
	otp = models.CharField(max_length=4)
	created = models.DateTimeField(auto_now_add=True)
	guesses_left = models.PositiveSmallIntegerField(default=3)
	successful = models.BooleanField(default=False)

	def __str__(self):
		return self.user.username

class TeamApplication(models.Model):
	from_user = models.ForeignKey(User)
	send = models.DateTimeField(auto_now=False, auto_now_add=True)
	to_team = models.ManyToManyField(Team)
	application_text = models.TextField()
	accepted = models.BooleanField(default=False)
	need_user_accept = models.BooleanField(default=False)
	need_info = models.BooleanField(default=False)
	need_info_comment = models.TextField(blank=True)
	refused = models.BooleanField(default=False)
	refused_comment = models.TextField(blank=True)

class EmailAndSmsMessages(models.Model):
	token = models.CharField(max_length=36)
	msgtype = models.CharField(max_length=36)
	team = models.ForeignKey(Team)
	members = models.ManyToManyField(TeamMembership)
	subject = models.CharField(max_length=50)
	message =  models.TextField(blank=True)

staff/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import TeamApplication, Team, TeamMembership, TShirt, DriversLicenceCategories, Language
from django.forms import ModelChoiceField, ModelMultipleChoiceField

class SignUpForm(UserCreationForm):
	postal_code = forms.CharField(max_length=10, required=True)
	phone_number = forms.CharField(max_length=16, required=True)

	class Meta:
		model = User
		fields = ('username', 'first_name', 'last_name', 'email', 'postal_code', 'phone_number', 'password1', 'password2', )

	def clean(self):
		cleaned_data = super(SignUpForm, self).clean()
		username = cleaned_data.get('username')
		if username and User.objects.filter(username__iexact=username).exists():
			self.add_error('username', 'A user with that username already exists.')
		return cleaned_data

class TshirtChoiceField(ModelChoiceField):
    def label_from_instance(self, obj):
        return obj.description

class DriversLicenceCategoriesMultipleChoiceField(ModelMultipleChoiceField):
    def label_from_instance(self, obj):
        return obj.category

class LanguageMultipleChoiceField(ModelMultipleChoiceField):
    def label_from_instance(self, obj):
        return obj.name

class UpdateProfileForm(forms.ModelForm):
	birthdate = forms.DateField(input_formats=['%d-%m-%Y'],required=False)
	phone_number = forms.CharField(max_length=16, required=True)
	phone_number_show = forms.BooleanField(required=False)
	emergency_number = forms.CharField(max_length=16, required=False)
	postal_code = forms.CharField(max_length=10, required=True)
	languages = LanguageMultipleChoiceField(queryset=Language.objects.all(),required=False)
	drivers_licence = DriversLicenceCategoriesMultipleChoiceField(queryset=DriversLicenceCategories.objects.all(),required=False)
	tshirt = TshirtChoiceField(queryset=TShirt.objects.all(),required=False)
	special_considerations = forms.CharField(required=False)
	class Meta:
		model = User
		fields = ('username', 'first_name', 'last_name', 'email', 'birthdate', 'phone_number', 'phone_number_show', 'emergency_number', 'postal_code', 'languages', 'drivers_licence', 'tshirt', 'special_considerations',)

class UpdateSociallinksForm(forms.ModelForm):
	facebook_link = forms.URLField(max_length=200, required=False)
	twitter_link = forms.URLField(max_length=200, required=False)
	soundcloud_link = forms.URLField(max_length=200, required=False)
	youtube_link = forms.URLField(max_length=200, required=False)
	class Meta:
		model = User
		fields = ('facebook_link','twitter_link','soundcloud_link','youtube_link', )

class UpdateProfileAvatar(forms.ModelForm):
	avatar = forms.ImageField()
	class Meta:
		model = User
		fields = ('avatar',)

class UpdateProfileBackground(forms.ModelForm):
	background = forms.ImageField()
	class Meta:
		model = User
		fields = ('background',)

class SendApplication(forms.ModelForm):
	class Meta:
		model = TeamApplication
		fields = ('from_user', 'to_team', 'application_text',)

class FeedbackSupportForm(forms.Form):
	first_name = forms.CharField(max_length=30, required=True)
	last_name = forms.CharField(max_length=30, required=True)
	email = forms.EmailField(required=True)
	message = forms.CharField(widget=forms.Textarea, required=True)

	class Meta:
		fields = ('username', 'first_name', 'last_name', 'email', 'message',)

class TeamSettings_GeneralForm(forms.ModelForm):
	class Meta:
		model = Team
		fields = ('name', 'accepts_applications',)

class UpdateTeamlogo(forms.ModelForm):
	logo = forms.ImageField()
	class Meta:
		model = Team
		fields = ('logo',)

class UpdateTeambackground(forms.ModelForm):
	background = forms.ImageField()
	class Meta:
		model = Team
		fields = ('background',)

class TeamSettings_DescriptionForm(forms.ModelForm):
	class Meta:
		model = Team
		fields = ('description',)

class TeamSettings_acceptForm(forms.ModelForm):
	class Meta:
		model = TeamMembership
		fields = ('user',)

class TeamSettings_needinfo_andrefuseForm(forms.Form):
	user = forms.IntegerField()
	comment = forms.CharField(widget=forms.Textarea, required=False)
	class Meta:
		fields = ('user', 'comment',)

class TeamSettings_AddForm(forms.ModelForm):
	class Meta:
		model = TeamMembership
		fields = ('user','team', 'leader')

staff/templates/user/settings.html
{% extends "base.html" %}

{% load static %}

{% block title %}
User Settings - Chaos, Genki
{% endblock %}

{% block header %}
<link rel="stylesheet" href="{% static 'css/usrsettings.css' %}">
<link rel="stylesheet" href="{% static 'intl-tel-input/css/intlTelInput.css' %}">
{% endblock %}

{% block content %}
<section role="content">
	<div class="container">
		<h1 class="line-top">Settings for {{ logged_in_user.extendeduser.nickname }}.</h1>
		{% if messages %}
		<div class="alert alert-success" role="alert">
			{% for message in messages %}
			<p>{{ message }}</p>
			{% endfor %}
		</div>
		{% endif %}
		<div>
			<a href="{% url 'user' requested_user.extendeduser.pk %}" class="vicbtn vicbtn-red vicbtn-bottom"><i class="fa fa-arrow-left" aria-hidden="true"></i> Back</a>
			<button type="button" class="vicbtn vicbtn-blue vicbtn-bottom" data-toggle="modal" data-target="#changepassword">Change Password</button>
		</div>
		<ul class="nav nav-tabs" id="usersettingsstab" role="tablist">
			<li class="nav-item">
				<a class="vic-tablink active" id="user-settings" href="{% url 'usersettings' logged_in_user.pk %}">General</a>
			</li>
			<li class="nav-item">
				<a class="vic-tablink" id="user-avatar"  href="{% url 'useravatar' logged_in_user.pk %}">Avatar</a>
			</li>
		</ul>
		<div class="row">
			<div class="col">
				<form onsubmit="SubmitSaveprofile();" action="{% url 'userprofileupdate' logged_in_user.pk %}" method="POST" name="saveProfileform">
					{% csrf_token %}
					<div class="custompanel no-m-bottom">
						<h3>Account <button type="button" class="vicbtn vicbtn-blue float-right" data-toggle="modal" data-target="#infomodal"><i class="fa fa-info" ></i> INFO</button></h3>
						<hr style="border-color:rgba(0, 0, 0, 1);">
						<div class="form-group">
							<label class="viclabelline-bottom" for="id_username">User/Nickname</label>
							<input type="text" class="victext-input vic-block full-width" name="username" maxlength="150" required id="id_username" placeholder="Victory" value="{{ logged_in_user.username }}">
							<small id="usernameHelpBlock" class="form-text text-muted">
								150 characters or fewer. Letters, digits and @/./+/-/_ only.
							</small>
						</div>
						<div class="form-row">
							<div class="form-group col-md-6">
								<label class="viclabelline-bottom" for="id_first_name">First Name</label>
								<input type="text" class="victext-input vic-block full-width" name="first_name" maxlength="30" required id="id_first_name" placeholder="Peter" value="{{ logged_in_user.first_name }}">
							</div>
							<div class="form-group col-md-6">
								<label class="viclabelline-bottom" for="id_last_name">Last Name</label>
								<input type="text" class="victext-input vic-block full-width" name="last_name" maxlength="30" required id="id_last_name" placeholder="Petersen" value="{{ logged_in_user.last_name }}">
							</div>
						</div>
						<div class="form-group">
							<label class="viclabelline-bottom vic-block" for="id_email">Email</label>
							<input type="email" class="victext-input settings-width" name="email" maxlength="254" required id="id_email" placeholder="Email@example.dk" value="{{ logged_in_user.email }}">
						</div>
						<div class="form-group">
							<label class="viclabelline-bottom vic-block" for="id_birthdate">Birthdate</label>
							<input type="text" class="victext-input settings-width" placeholder="dd-mm-yyyy" name="birthdate" id="id_birthdate" value="{{ logged_in_user.extendeduser.birthdate|date:'d-m-Y' }}">
						</div>
						<div class="form-group">
							<label class="viclabelline-bottom vic-block" for="id_phone_number">Phone number</label>
							<input type="tel" class="victext-input settings-width" name="phone_number" required id="id_phone_number" value="{{ logged_in_user.extendeduser.phone_number }}">
						</div>
						<div class="form-check">
					    <label class="form-check-label">
					      <input id="id_phone_number_show" {% if logged_in_user.extendeduser.phone_number_show == 1 %} checked {% endif %} name="phone_number_show" type="checkbox" class="form-check-input">
					      Show phone number?
					    </label>
					  </div>
						<div class="form-group">
							<label class="viclabelline-bottom vic-block" for="id_emergency_number">EMC(emergency) Phone number</label>
							<input type="tel" class="victext-input settings-width" name="emergency_number" id="id_emergency_number" value="{{ logged_in_user.extendeduser.emergency_number }}">
						</div>
						<div class="form-group">
							<label class="viclabelline-bottom vic-block" for="id_postal_code">Postal code</label>
							<input type="number" class="victext-input settings-width" name="postal_code" maxlength="10" id="id_postal_code" placeholder="1577" value="{{ logged_in_user.extendeduser.postal_code }}">
						</div>
						<div class="form-group">
							<label class="viclabelline-bottom vic-block">Language(s)</label>
							<select id="id_languages" name="languages" class="languages settings-width" multiple="multiple">
								{% for lang in language %}
									<option {%for userlang in logged_in_user.extendeduser.languages.all %}{%if userlang.id == lang.id %}selected{%endif%}{%endfor%} value="{{lang.id}}">{{lang.name}}</option>
								{% endfor %}
							</select>
						</div>
						<div class="form-group">
							<label class="viclabelline-bottom vic-block">Driver License(s)</label>
							<select id="id_drivers_licence" name="drivers_licence" class="drivercategories settings-width" multiple="multiple">
								{% for category in driverslicence %}
								<option {%for drilic in logged_in_user.extendeduser.drivers_licence.all %}{%if drilic.id == category.id %}selected{%endif%}{%endfor%} value="{{category.id}}">{{category.category}}</option>
								{% endfor %}
							</select>
						</div>
						<div class="form-group">
							<label class="viclabelline-bottom vic-block">T-Shirt size (Size chart)</label>
							<select id="id_tshirt" name="tshirt" class="victext-input settings-width">
								{% for tshi in tshirt %}
								<option {%if logged_in_user.extendeduser.tshirt.id == tshi.id %}selected{%endif%} value="{{tshi.id}}">{{tshi.description}}</option>
								{% endfor %}
							</select>
						</div>
						<div class="form-group">
							<label class="viclabelline-bottom vic-block" for="id_specialcons">Special Considerations(Allergies and so...)</label>
							<textarea class="victext-input w-100" id="id_special_considerations" name="special_considerations" rows="3">{% autoescape on %}{{ logged_in_user.extendeduser.special_considerations}}{% endautoescape off %}</textarea>
						</div>
					</div>
					<button type="submit" class="vicbtn vicbtn-green w-100">Save</button>
				</form>
			</div>
			<div class="col">
				<div class="custompanel no-m-bottom">
					<h3>Settings</h3>
					<hr style="border-color:rgba(0, 0, 0, 1);">
					<p>Coming Soon.</p>
				</div>
				<form action="{% url 'usersociallinks' logged_in_user.pk %}" method="post">
					{% csrf_token %}
				<div class="custompanel no-m-bottom">
					<h3>Social links</h3>
					<hr style="border-color:rgba(0, 0, 0, 1);">
					<div class="form-group">
						<label class="viclabelline-bottom vic-block" for="id_facebook-link">Facebook (URL)</label>
						<input type="text" class="victext-input settings-width" name="facebook_link" maxlength="250" id="id_facebook-link" placeholder="www.facebook.com/yournamehere" value='{{logged_in_user.extendeduser.facebook_link|safe}}'>
					</div>
					<div class="form-group">
						<label class="viclabelline-bottom vic-block" for="id_twitter-link">Twitter (URL)</label>
						<input type="text" class="victext-input settings-width" name="twitter_link" maxlength="250" id="id_twitter-link" placeholder="" value='{{logged_in_user.extendeduser.twitter_link|safe}}'>
					</div>
					<div class="form-group">
						<label class="viclabelline-bottom vic-block" for="id_soundcloud-link">Soundcloud (URL)</label>
						<input type="text" class="victext-input settings-width" name="soundcloud_link" maxlength="250" id="id_soundcloud-link" placeholder="" value='{{logged_in_user.extendeduser.soundcloud_link|safe}}'>
					</div>
					<div class="form-group">
						<label class="viclabelline-bottom vic-block" for="id_youtube-link">Youtube (URL)</label>
						<input type="text" class="victext-input settings-width" name="youtube_link" maxlength="250" id="id_youtube-link" placeholder="" value='{{logged_in_user.extendeduser.youtube_link|safe}}'>
					</div>
					<p>More to come.</p>
				</div>
				<button type="submit" class="vicbtn vicbtn-green w-100">Save</button>
				</form>
			</div>
		</div>
	</div>

</section>

{% endblock %}

{% block scripts %}
<script src="{% static 'intl-tel-input/js/intlTelInput.js' %}"></script>
<script src="{% static 'intl-tel-input/js/utils.js' %}"></script>
<script src="{% static 'js/application.js' %}"></script>
<script src="{% static 'js/profile.js' %}"></script>
{% endblock %}

{% block modals %}

<div class="modal fade" id="infomodal" tabindex="-1" role="dialog" aria-labelledby="infomodal" aria-hidden="true">
	<div class="modal-dialog modal-lg" role="document">
		<div class="custompanel">
			<div class="modal-header">
				<h5 class="modal-title" id="infoModalLabel">Info about the fields</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
				<div class="modal-body">
					<p>You are properly vondering what fields will be shown and what are hidden so we made a list.</p>
					<p>Keep in mind that in a future update you can hide everything beside your name and nick.</p>
					<br>
					<p>So Simply Who can see what</p>
					<br>
					<ul>
						<li><b>The Reactor</b> -> Victor The Owner of The Reactor(the people behind Genki) is the only and i mean only one who has access to see all your info.</li>
						<li><b>Medic and security</b> -> For the best reasons for our medics and security to help you most they are able to get the necessary info like EMC number and special Considerations</li>
						<li><b>Developers (Meicki And Denis)</b> - they can see the info due to they developing the platform.</li>
						<li><b>Teamleaders</b> - well they can only see the necessary info like your driver license and what languages you can.</li>
						<li><b>What about the rest</b> - Well thats up to you for now only Name, Nick, Email, Phone(if u want it to show) and social links are the only one people can see right now. (THEY WILL Need an account for that to!)</li>
					</ul>
					<p><b>Last updated: 08/03/2018</b></p>
				</div>
				<div class="modal-footer">
					<button type="button" class="vicbtn vicbtn-blue" data-dismiss="modal">Close</button>
				</div>
		</div>
	</div>
</div>
<!-- Modal -->
<div class="modal fade" id="changepassword" tabindex="-1" role="dialog" aria-labelledby="changepassword" aria-hidden="true">
	<div class="modal-dialog modal-lg" role="document">
		<div class="custompanel">
			<div class="modal-header">
				<h5 class="modal-title" id="ChangePasswordModalLabel">Change password</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<form action="{% url 'user_change_password' requested_user.extendeduser.pk %}" method="post">
				{% csrf_token %}
				<div class="modal-body">
					<div class="form-group">
						<label for="id_old_password">Old Password</label>
						<input id="id_old_password" class="victext-input vic-block full-width" type="password" name="old_password">
					</div>
					<div class="form-group">
						<label for="id_new_password1">New Password</label>
						<input id="id_new_password1" class="victext-input vic-block full-width" type="password" name="new_password1">
						<small id="password1HelpBlock" class="form-text text-muted">
							<ul>
								<li>Your password can't be too similar to your other personal information.</li>
								<li>Your password must contain at least 8 characters.</li>
								<li>Your password can't be a commonly used password.</li>
								<li>Your password can't be entirely numeric.</li>
							</ul>
						</small>
					</div>
					<div class="form-group">
						<label for="id_new_password2">New Password Confirmation</label>
						<input id="id_new_password2" class="victext-input vic-block full-width" type="password" name="new_password2">
					</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="vicbtn vicbtn-blue" data-dismiss="modal">Close</button>
					<button type="submit" class="vicbtn vicbtn-green">Change</button>
				</div>
			</form>
		</div>
	</div>
</div>

{% endblock %}