staff/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^login/$', views.login, name='login'),
	url(r'^logout/$', views.logout, name='logout'),
	url(r'^register/$', views.register, name='register'),
	url(r'^users/$', views.users, name='users'),
	url(r'^message/$', views.webmessage, name='webmessage'),
	url(r'^users/(?P<user_pk>[0-9]+)/$', views.user, name='user'),
	url(r'^users/(?P<user_pk>[0-9]+)/settings/$', views.usersettings, name='usersettings'),
	url(r'^users/(?P<user_pk>[0-9]+)/settings/profile/$', views.userprofileupdate, name='userprofileupdate'),
	url(r'^users/(?P<user_pk>[0-9]+)/settings/social/$', views.usersociallinks, name='usersociallinks'),
	url(r'^users/(?P<user_pk>[0-9]+)/settings/avatar/$', views.useravatar, name='useravatar'),
	url(r'^users/(?P<user_pk>[0-9]+)/settings/background/$', views.userbackground, name='userbackground'),
	url(r'^users/(?P<user_pk>[0-9]+)/settings/change_password$', views.user_change_password, name='user_change_password'),
	url(r'^teams/$', views.teams, name='teams'),
	url(r'^teams/(?P<team_pk>[0-9]+)/$', views.team, name='team'),
	url(r'^teams/(?P<team_pk>[0-9]+)/settings/$', views.teamsettings_general, name='teamsettings_general'),
	url(r'^teams/(?P<team_pk>[0-9]+)/settings/message$', views.teamsettings_message, name='teamsettings_message'),
	url(r'^teams/(?P<team_pk>[0-9]+)/settings/logo/$', views.teamsettings_logo, name='teamsettings_logo'),
	url(r'^teams/(?P<team_pk>[0-9]+)/settings/background/$', views.teamsettings_background, name='teamsettings_background'),
	url(r'^teams/(?P<team_pk>[0-9]+)/settings/description/$', views.teamsettings_description, name='teamsettings_description'),
	url(r'^teams/(?P<team_pk>[0-9]+)/settings/members/$', views.teamsettings_members, name='teamsettings_members'),
	url(r'^teams/(?P<team_pk>[0-9]+)/settings/members/add/$', views.teamsettings_members_add, name='teamsettings_members_add'),
	url(r'^teams/(?P<team_pk>[0-9]+)/settings/members/delete/$', views.teamsettings_members_delete, name='teamsettings_members_delete'),
	url(r'^teams/(?P<team_pk>[0-9]+)/settings/applications/$', views.teamsettings_applications, name='teamsettings_applications'),
	url(r'^teams/(?P<team_pk>[0-9]+)/settings/applications/accepted/$', views.teamsettings_accept_applications, name='teamsettings_accept_applications'),
	url(r'^teams/(?P<team_pk>[0-9]+)/settings/applications/needinfo/$', views.teamsettings_needinfo_applications, name='teamsettings_needinfo_applications'),
	url(r'^teams/(?P<team_pk>[0-9]+)/settings/applications/refuse/$', views.teamsettings_refuse_applications, name='teamsettings_refuse_applications'),
	url(r'^apply/$', views.apply, name='apply'),
	url(r'^apply/sent/$', views.applysent, name='applysent'),
	url(r'^apply/accept/$', views.useraccept, name='useraccept'),
	url(r'^apply/delete/$', views.applydelete, name='applydelete'),
	url(r'^contact/$', views.contact, name='contact'),
	## PASSWORD RESET
	url(r'^password_reset/$', auth_views.password_reset, {
		'template_name'			  : 'reset/password_reset_form.html',
		'subject_template_name'	  : 'email/password_reset_subject.txt',
		'html_email_template_name': 'email/password_reset_email.html',
		'from_email'			  : 'info@victory.genki.dk'
		}, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done,{'template_name': 'reset/password_reset_done.html'}, name='password_reset_done'),
	url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm,{'template_name': 'reset/password_reset_confirm.html'}, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete,{'template_name': 'reset/password_reset_complete.html'}, name='password_reset_complete'),
]

victory/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^', include('staff.urls')),
	url(r'^admin/', admin.site.urls),
]

staff/models.py
from django.db import models

from django.contrib.auth.models import User
from django.core.validators import RegexValidator, MinValueValidator, MaxValueValidator
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.

class Team(models.Model):
	name = models.CharField(max_length=50)
	logo = models.ImageField(upload_to='teams/avatars', default='static/img/userpreload.png')
	background = models.ImageField(upload_to='teams/backgrounds', default='static/img/userpreload.png')
	description = models.TextField(blank=True)
	people_needed = models.PositiveSmallIntegerField()
	members = models.ManyToManyField(User, through='TeamMembership')
	accepts_applications = models.BooleanField()

	@property
	def teamleaders_listable(self):
		leaders = self.members.filter(teammembership__leader=True)
		return ", ".join(l.extendeduser.nickname for l in leaders)

	@property
	def multiple_teamleaders(self):
		if len(self.members.filter(teammembership__leader=True)) > 1:
			return True
		else:
			return False

	def __str__(self):
		return self.name

class TeamMembership(models.Model):
	user = models.ForeignKey(User)
	team = models.ForeignKey(Team)
	leader = models.BooleanField(default=False)
	groupleader = models.BooleanField(default=False)

class DriversLicenceCategories(models.Model): # No plural
	category = models.CharField(max_length=3)

	def __str__(self):
		return self.category

class Language(models.Model):
	name = models.CharField(max_length=16)

	def __str__(self):
		return self.name

class TShirt(models.Model):
	description = models.CharField(max_length=32)

class Sock(models.Model):
	description = models.CharField(max_length=32)

class ExtendedUser(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	nickname = models.CharField(max_length=20)
	birthdate = models.DateField(null=True, blank=True)
	postal_code = models.CharField(max_length=10)
	phone_number_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+4570131415'. Up to 15 digits allowed.")
	phone_number = models.CharField(max_length=16, validators=[phone_number_regex], blank=True)
	phone_number_show = models.BooleanField(default=False)
	emergency_number = models.CharField(max_length=16, validators=[phone_number_regex], blank=True)
	drivers_licence = models.ManyToManyField(DriversLicenceCategories, blank=True)
	avatar = models.ImageField(upload_to='users/avatars', default='static/img/userpreload.png')
	background = models.ImageField(upload_to='users/backgrounds', default='static/img/userpreload.png')
	team = models.ForeignKey(Team, null=True, blank=True)
	languages = models.ManyToManyField(Language, blank=True)
	tshirt = models.ForeignKey(TShirt, null=True, blank=True)
	sock = models.ForeignKey(Sock, null=True, blank=True)
	facebook_link = models.URLField(max_length=200, blank=True, null=True)
	twitter_link = models.URLField(max_length=200, blank=True, null=True)
	soundcloud_link = models.URLField(max_length=200, blank=True, null=True)
	youtube_link = models.URLField(max_length=200, blank=True, null=True)
	child_record = models.DateField(null=True, blank=True)
	special_considerations = models.TextField(blank=True)

@receiver(post_save, sender=User)
def update_user_extendeduser(sender, instance, created, **kwargs):
    if created:
        ExtendedUser.objects.create(user=instance)
    instance.extendeduser.save()

class Article(models.Model):
	author = models.ForeignKey(User)
	title = models.CharField(max_length=64)
	created = models.DateTimeField(null=True)
	body = models.TextField()

	def __str__(self):
		return self.title

class Alert(models.Model):
	title = models.CharField(max_length=32)
	body = models.TextField(blank=True)
	start = models.DateTimeField()
	end = models.DateTimeField()

class UnauthenticatedSession(models.Model):
	user = models.ForeignKey(User)
	token = models.CharField(max_length=36)
	otp = models.CharField(max_length=4)
	created = models.DateTimeField(auto_now_add=True)
	guesses_left = models.PositiveSmallIntegerField(default=3)
	successful = models.BooleanField(default=False)

	def __str__(self):
		return self.user.username

class TeamApplication(models.Model):
	from_user = models.ForeignKey(User)
	send = models.DateTimeField(auto_now=False, auto_now_add=True)
	to_team = models.ManyToManyField(Team)
	application_text = models.TextField()
	accepted = models.BooleanField(default=False)
	need_user_accept = models.BooleanField(default=False)
	need_info = models.BooleanField(default=False)
	need_info_comment = models.TextField(blank=True)
	refused = models.BooleanField(default=False)
	refused_comment = models.TextField(blank=True)

class EmailAndSmsMessages(models.Model):
	token = models.CharField(max_length=36)
	msgtype = models.CharField(max_length=36)
	team = models.ForeignKey(Team)
	members = models.ManyToManyField(TeamMembership)
	subject = models.CharField(max_length=50)
	message =  models.TextField(blank=True)

staff/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import TeamApplication, Team, TeamMembership, TShirt, DriversLicenceCategories, Language
from django.forms import ModelChoiceField, ModelMultipleChoiceField

class SignUpForm(UserCreationForm):
	postal_code = forms.CharField(max_length=10, required=True)
	phone_number = forms.CharField(max_length=16, required=True)

	class Meta:
		model = User
		fields = ('username', 'first_name', 'last_name', 'email', 'postal_code', 'phone_number', 'password1', 'password2', )

	def clean(self):
		cleaned_data = super(SignUpForm, self).clean()
		username = cleaned_data.get('username')
		if username and User.objects.filter(username__iexact=username).exists():
			self.add_error('username', 'A user with that username already exists.')
		return cleaned_data

class TshirtChoiceField(ModelChoiceField):
    def label_from_instance(self, obj):
        return obj.description

class DriversLicenceCategoriesMultipleChoiceField(ModelMultipleChoiceField):
    def label_from_instance(self, obj):
        return obj.category

class LanguageMultipleChoiceField(ModelMultipleChoiceField):
    def label_from_instance(self, obj):
        return obj.name

class UpdateProfileForm(forms.ModelForm):
	birthdate = forms.DateField(input_formats=['%d-%m-%Y'],required=False)
	phone_number = forms.CharField(max_length=16, required=True)
	phone_number_show = forms.BooleanField(required=False)
	emergency_number = forms.CharField(max_length=16, required=False)
	postal_code = forms.CharField(max_length=10, required=True)
	languages = LanguageMultipleChoiceField(queryset=Language.objects.all(),required=False)
	drivers_licence = DriversLicenceCategoriesMultipleChoiceField(queryset=DriversLicenceCategories.objects.all(),required=False)
	tshirt = TshirtChoiceField(queryset=TShirt.objects.all(),required=False)
	special_considerations = forms.CharField(required=False)
	class Meta:
		model = User
		fields = ('username', 'first_name', 'last_name', 'email', 'birthdate', 'phone_number', 'phone_number_show', 'emergency_number', 'postal_code', 'languages', 'drivers_licence', 'tshirt', 'special_considerations',)

class UpdateSociallinksForm(forms.ModelForm):
	facebook_link = forms.URLField(max_length=200, required=False)
	twitter_link = forms.URLField(max_length=200, required=False)
	soundcloud_link = forms.URLField(max_length=200, required=False)
	youtube_link = forms.URLField(max_length=200, required=False)
	class Meta:
		model = User
		fields = ('facebook_link','twitter_link','soundcloud_link','youtube_link', )

class UpdateProfileAvatar(forms.ModelForm):
	avatar = forms.ImageField()
	class Meta:
		model = User
		fields = ('avatar',)

class UpdateProfileBackground(forms.ModelForm):
	background = forms.ImageField()
	class Meta:
		model = User
		fields = ('background',)

class SendApplication(forms.ModelForm):
	class Meta:
		model = TeamApplication
		fields = ('from_user', 'to_team', 'application_text',)

class FeedbackSupportForm(forms.Form):
	first_name = forms.CharField(max_length=30, required=True)
	last_name = forms.CharField(max_length=30, required=True)
	email = forms.EmailField(required=True)
	message = forms.CharField(widget=forms.Textarea, required=True)

	class Meta:
		fields = ('username', 'first_name', 'last_name', 'email', 'message',)

class TeamSettings_GeneralForm(forms.ModelForm):
	class Meta:
		model = Team
		fields = ('name', 'accepts_applications',)

class UpdateTeamlogo(forms.ModelForm):
	logo = forms.ImageField()
	class Meta:
		model = Team
		fields = ('logo',)

class UpdateTeambackground(forms.ModelForm):
	background = forms.ImageField()
	class Meta:
		model = Team
		fields = ('background',)

class TeamSettings_DescriptionForm(forms.ModelForm):
	class Meta:
		model = Team
		fields = ('description',)

class TeamSettings_acceptForm(forms.ModelForm):
	class Meta:
		model = TeamMembership
		fields = ('user',)

class TeamSettings_needinfo_andrefuseForm(forms.Form):
	user = forms.IntegerField()
	comment = forms.CharField(widget=forms.Textarea, required=False)
	class Meta:
		fields = ('user', 'comment',)

class TeamSettings_AddForm(forms.ModelForm):
	class Meta:
		model = TeamMembership
		fields = ('user','team', 'leader')

staff/templates/base.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<meta name="apple-mobile-web-app-capable" content="yes">
		<link href="{% static 'img/icons/apple-touch-icon.png' %}" rel="apple-touch-icon" />
		<link href="{% static 'img/icons/apple-touch-icon-152x152.png' %}" rel="apple-touch-icon" sizes="152x152" />
		<link href="{% static 'img/icons/apple-touch-icon-167x167.png' %}" rel="apple-touch-icon" sizes="167x167" />
		<link href="{% static 'img/icons/apple-touch-icon-180x180.png' %}" rel="apple-touch-icon" sizes="180x180" />
		<link href="{% static 'img/icons/icon-hires.png' %}" rel="icon" sizes="192x192" />
		<link href="{% static 'img/icons/icon-normal.png' %}" rel="icon" sizes="128x128" />
		<link rel="shortcut icon" type="image/x-icon" href="{% static 'img/icons/favicon.ico' %}" />
		<meta name="theme-color" content="#1997c6" />
		<title>
			{% block title %}
			Genki Staff
			{% endblock %}
		</title>
		<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
		<link rel="stylesheet" href="{% static 'css/light.css' %}">
		<link rel="stylesheet" href="{% static 'font-awesome/css/font-awesome.min.css' %}">
		{% block header %}
		{% endblock %}
	</head>
	<body>
		<header>
			<nav class="mainnavbar">
				<a class="alogo" href="{% url 'index' %}">
					<img class="logob" src="{% static 'img/logo.png' %}">
				</a>
				<div class="navdivlinkscustom">
					<ul class="nav brs aaj">
						{% url 'index' as url_index %}
						<li class="qp">
							<a class="qn navicons {% if request.get_full_path == url_index %} vic-active {% endif %}" href="{% url 'index' %}" title="Dashboard" data-placement="right">
								<i class="fa fa-home" aria-hidden="true"></i>
								<small class="brt axz">Dashboard</small>
							</a>
						</li>

						{% url 'teams' as url_teams %}
						<li class="qp">
							<a class="qn navicons {% if request.get_full_path == url_teams %} vic-active {% endif %}" href="{{ url_teams }}" title="Teams" data-placement="right">
								<i class="fa fa-book" aria-hidden="true"></i>
								<small class="brt axz">Teams</small>
							</a>
						</li>

						{% for team in thisdoesnotexistplz %}
						<li class="qp">
							<a class="qn navicons" href="/staff/teams/0" title="My Team" data-placement="right">
								<i class="fa fa-bookmark" aria-hidden="true"></i>
								<small class="brt axz">My Team</small>
							</a>
						</li>
						{% endfor %}

						{% if user.is_authenticated %}
						{% url 'users' as url_users %}
						<li class="qp">
							<a class="qn navicons {% if request.get_full_path == url_users %} vic-active {% endif %}" href="{% url 'users' %}" title="All users" data-placement="right">
								<i class="fa fa-users" aria-hidden="true"></i>
								<small class="brt axz">Users</small>
							</a>
						</li>
						{% endif %}

						{% if user.is_authenticated %}
						{% url 'user' request.user.pk as url_user %}
						<li class="qp">
							<a class="qn navicons {% if request.get_full_path == url_user %} vic-active {% endif %}" href="{{ url_user }}" title="My Profile" data-placement="right">
								<img src="{{ logged_in_user.extendeduser.avatar.url }}" class="wc">
								<small class="brt axz">Profile</small>
							</a>
						</li>
						{% endif %}

						{% if thisisnotsupposedtoexist %}
						<li class="qp">
							<a class="qn navicons" href="{% url 'index' %}" title="Chaos Settings" data-placement="right">
								<i class="fa fa-cogs" aria-hidden="true"></i>
								<small class="brt axz">Settings</small>
							</a>
						</li>
						{% endif %}

						{% if user.is_authenticated %}
						<li class="qp">
							<a class="qn navicons" href="{% url 'logout' %}" title="Log out" data-placement="right">
								<i class="fa fa-sign-out" aria-hidden="true"></i>
								<small class="brt axz">Log out</small>
							</a>
						</li>
						{% else %}
						{% url 'login' as url_login %}
						<li class="qp">
							<a class="qn navicons {% if request.get_full_path == url_login %} vic-active {% endif %}" href="{% url 'login' %}" title="Log in" data-placement="right">
								<i class="fa fa-sign-in" aria-hidden="true"></i>
								<small class="brt axz">Log in</small>
							</a>
						</li>
						{% url 'register' as url_register %}
						<li class="qp">
							<a class="qn navicons {% if request.get_full_path == url_register %} vic-active {% endif %}" href="{% url 'register' %}" title="Register" data-placement="right">
								<i class="fa fa-user-plus" aria-hidden="true"></i>
								<small class="brt axz">Register</small>
							</a>
						</li>
						{% endif %}
					</ul>
				 </div>
			</nav>
		</header>

		{% block content %}
		<section role="content">
			<div class="container">
				<h1 class="line-top">Nothing to see here.</h1>
			</div>
		</section>
		{% endblock %}
		<div id="feedback_btn">
			<div type="button" title="Feedback & support" data-toggle="modal" data-target="#feedback_and_support" class="feedb-btn">
				<i class="fa fa-comments fa-2x feedb-icon" aria-hidden="true"></i>
			</div>
		</div>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
		<script src="{% static 'js/bootstrap.min.js' %}"></script>
		<script src="{% static 'js/custom.js' %}"></script>
		{% block scripts %}
		{% endblock %}
	</body>
</html>

{% block modals %}
{% endblock %}

<div class="modal fade" id="feedback_and_support" tabindex="-1" role="dialog" aria-labelledby="feedback_and_support" aria-hidden="true">
	<div class="modal-dialog modal-lg" role="document">
		<div class="custompanel">
			<div class="modal-header">
				<h5 class="modal-title" id="ChangePasswordModalLabel">Feedback and support</h5><br>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<form action="{% url 'contact' %}" method="POST">
				{% csrf_token %}
				<div class="modal-body">
					<div class="form-row">
						<div class="form-group col-md-6">
							<label class="viclabelline-bottom" for="id_first_name">First Name</label>
							<input type="text" class="victext-input vic-block full-width" name="first_name" maxlength="30" required id="id_first_name" placeholder="Peter" {% if user.is_authenticated %} value="{{ logged_in_user.first_name }}" {% endif %}>
						</div>
						<div class="form-group col-md-6">
							<label class="viclabelline-bottom" for="id_last_name">Last Name</label>
							<input type="text" class="victext-input vic-block full-width" name="last_name" maxlength="30" required id="id_last_name" placeholder="Petersen" {% if user.is_authenticated %} value="{{ logged_in_user.last_name }}" {% endif %}>
						</div>
					</div>
					<div class="form-group">
						<label class="viclabelline-bottom" for="id_email">Email</label>
						<input type="email" class="victext-input vic-block full-width" name="email" maxlength="254" required id="id_email" placeholder="Email@example.dk" {% if user.is_authenticated %} value="{{ logged_in_user.email }}" {% endif %}>
					</div>
					<div class="form-group">
						<label for="id_message">Message</label>
						<textarea rows="4" id="id_message" class="victext-input vic-block full-width" type="text" placeholder="Sometext...." name="message"></textarea>
					</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="vicbtn vicbtn-blue" data-dismiss="modal">Close</button>
					<button type="submit" class="vicbtn vicbtn-green">Send</button>
				</div>
			</form>
		</div>
	</div>
</div>

staff/templates/dashboard.html
{% extends "base.html" %}

{% load static %}

{% block title %}
Victory
{% endblock %}

{% block content %}
<section role="content">
	<div class="container">
		<h1 class="line-top">Hello {{ user.extendeduser.nickname }}.</h1>
		{% if messages %}
		<div class="alert alert-success" role="alert">
			{% for message in messages %}
			<p>{{ message }}</p>
			{% endfor %}
		</div>
		{% endif %}
		<div class="custompanel">
			<h4>News.</h4>
			{% if searchfunctionisimplemented %}
			<div style="margin-bottom:10px;">
				<form class="search-width" style="display: inline-flex;" action="search" method="post">
					<input class="victext-input" type="text" placeholder="Search" name="search" value="">
					<button type="submit" class="vicbtn vicbtn-blue vic-bb-3-blue">Search</button>
				</form>
			</div>
			{% endif %}
			{% for article in articles %}
			<div class="post">
				<div class="postinfo">
					<p class="postowner"><a href="{% url 'user' article.author.pk %}">{{ article.author.extendeduser.nickname }}</a><span class="float-right">{{ article.created|date:"F j, Y, H:i"}}</span></p>
					<p class="posttitle line-topsmall">{{ article.title }}</p>
				</div>
				<div class="postcontent">
					{{ article.body|safe|linebreaksbr }}
				</div>
			</div>
			{% endfor %}
		</div>
	</div>
</section>
{% endblock %}

staff/templates/register.html
{% extends "base.html" %}

{% load static %}

{% block header %}
<link rel="stylesheet" href="{% static 'css/login.css' %}">
<link rel="stylesheet" href="{% static 'intl-tel-input/css/intlTelInput.css' %}">
{% endblock %}

{% block title %}
Register
{% endblock %}

{% block content %}
<div class="custompanel">
	<div class="logoimg">
		<img class="img-responsive" src="{% static 'img/crewlogo.png' %}">
	</div>
	<div class="text">
		<h3>Register</h3>
	</div>
	<hr>
	{% if form.errors %}
	<div class="alert alert-danger" role="alert">
		<ul>
		{% for key,value in form.errors.items %}
			<li>{{ key|escape }} : {{ value|escape }}</li>
		{% endfor %}
		</ul>
	</div>
	{% endif %}
	<form action="" method="POST" onsubmit="SubmitRegister();">
		{% csrf_token %}
		<div class="form-group">
			<label class="viclabelline-bottom" for="id_username">User/nickname</label>
			<input type="text" class="victext-input vic-block full-width" name="username" maxlength="150" required id="id_username" placeholder="Victory">
			<small class="form-text text-muted">
				50 characters or fewer. Letters, digits and @/./+/-/_ only.
			</small>
		</div>
		<div class="form-row">
			<div class="form-group col-md-6">
				<label class="viclabelline-bottom" for="id_first_name">First Name</label>
				<input type="text" class="victext-input vic-block full-width" name="first_name" maxlength="30" required id="id_first_name" placeholder="Peter">
			</div>
			<div class="form-group col-md-6">
				<label class="viclabelline-bottom" for="id_last_name">Last Name</label>
				<input type="text" class="victext-input vic-block full-width" name="last_name" maxlength="30" required id="id_last_name" placeholder="Petersen">
			</div>
		</div>
		<div class="form-group">
			<label class="viclabelline-bottom" for="id_email">Email</label>
			<input type="email" class="victext-input vic-block full-width" name="email" maxlength="254" required id="id_email" placeholder="Email@example.dk">
		</div>
		<div class="form-group">
			<label class="viclabelline-bottom" for="id_phone_number">Phone (Mobile with countrycode)</label>
			<input type="tel" class="victext-input vic-block full-width" name="phone_number" maxlength="16" required id="id_phone_number" placeholder="Phone number">
			<small class="form-text text-muted">
				Used to contact you and also for 2 factor authentication.
			</small>
		</div>
		<div class="form-group">
			<label class="viclabelline-bottom" for="id_postal_code">Postal code</label>
			<input type="text" class="victext-input vic-block full-width" name="postal_code" maxlength="10" required id="id_postal_code" placeholder="1577">
		</div>
		<hr>
		<hr>
		<div class="form-group">
			<label class="viclabelline-bottom" for="id_password1">Password</label>
			<input type="password" class="victext-input vic-block full-width" name="password1" required id="id_password1">
			<small id="password1HelpBlock" class="form-text text-muted">
				<ul>
					<li>Your password can't be too similar to your other personal information</li>
					<li>Least 8 characters</li>
					<li>Can't be entirely numeric</li>
				</ul>
			</small>
		</div>
		<div class="form-group">
			<label class="viclabelline-bottom" for="id_password2">Retype Password</label>
			<input type="password" class="victext-input vic-block full-width" name="password2" required id="id_password2">
			<small id="password2HelpBlock" class="form-text text-muted">
				Enter the same password as before, for verification.
			</small>
		</div>
		<div id="passwordchecking" style="display:none;" class="alert alert-danger" role="alert"></div>
		<hr>
		<button type="submit" class="vicbtn vicbtn-blue vicbtn-bottom full-width"><strong>Register</strong></button>
		<a href="{{ request.META.HTTP_REFERER }}" class="vicbtn vicbtn-red full-width"><i class="fa fa-arrow-left" aria-hidden="true"></i> Back</a>
	</form>
</div>
{% endblock %}

{% block scripts %}
<script src="{% static 'intl-tel-input/js/intlTelInput.js' %}"></script>
<script src="{% static 'intl-tel-input/js/utils.js' %}"></script>
<script src="{% static 'js/login.js' %}"></script>
{% endblock %}