staff/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^login/$', views.login, name='login'),
	url(r'^logout/$', views.logout, name='logout'),
	url(r'^register/$', views.register, name='register'),
	url(r'^users/$', views.users, name='users'),
	url(r'^message/$', views.webmessage, name='webmessage'),
	url(r'^users/(?P<user_pk>[0-9]+)/$', views.user, name='user'),
	url(r'^users/(?P<user_pk>[0-9]+)/settings/$', views.usersettings, name='usersettings'),
	url(r'^users/(?P<user_pk>[0-9]+)/settings/profile/$', views.userprofileupdate, name='userprofileupdate'),
	url(r'^users/(?P<user_pk>[0-9]+)/settings/social/$', views.usersociallinks, name='usersociallinks'),
	url(r'^users/(?P<user_pk>[0-9]+)/settings/avatar/$', views.useravatar, name='useravatar'),
	url(r'^users/(?P<user_pk>[0-9]+)/settings/background/$', views.userbackground, name='userbackground'),
	url(r'^users/(?P<user_pk>[0-9]+)/settings/change_password$', views.user_change_password, name='user_change_password'),
	url(r'^teams/$', views.teams, name='teams'),
	url(r'^teams/(?P<team_pk>[0-9]+)/$', views.team, name='team'),
	url(r'^teams/(?P<team_pk>[0-9]+)/settings/$', views.teamsettings_general, name='teamsettings_general'),
	url(r'^teams/(?P<team_pk>[0-9]+)/settings/message$', views.teamsettings_message, name='teamsettings_message'),
	url(r'^teams/(?P<team_pk>[0-9]+)/settings/logo/$', views.teamsettings_logo, name='teamsettings_logo'),
	url(r'^teams/(?P<team_pk>[0-9]+)/settings/background/$', views.teamsettings_background, name='teamsettings_background'),
	url(r'^teams/(?P<team_pk>[0-9]+)/settings/description/$', views.teamsettings_description, name='teamsettings_description'),
	url(r'^teams/(?P<team_pk>[0-9]+)/settings/members/$', views.teamsettings_members, name='teamsettings_members'),
	url(r'^teams/(?P<team_pk>[0-9]+)/settings/members/add/$', views.teamsettings_members_add, name='teamsettings_members_add'),
	url(r'^teams/(?P<team_pk>[0-9]+)/settings/members/delete/$', views.teamsettings_members_delete, name='teamsettings_members_delete'),
	url(r'^teams/(?P<team_pk>[0-9]+)/settings/applications/$', views.teamsettings_applications, name='teamsettings_applications'),
	url(r'^teams/(?P<team_pk>[0-9]+)/settings/applications/accepted/$', views.teamsettings_accept_applications, name='teamsettings_accept_applications'),
	url(r'^teams/(?P<team_pk>[0-9]+)/settings/applications/needinfo/$', views.teamsettings_needinfo_applications, name='teamsettings_needinfo_applications'),
	url(r'^teams/(?P<team_pk>[0-9]+)/settings/applications/refuse/$', views.teamsettings_refuse_applications, name='teamsettings_refuse_applications'),
	url(r'^apply/$', views.apply, name='apply'),
	url(r'^apply/sent/$', views.applysent, name='applysent'),
	url(r'^apply/accept/$', views.useraccept, name='useraccept'),
	url(r'^apply/delete/$', views.applydelete, name='applydelete'),
	url(r'^contact/$', views.contact, name='contact'),
	## PASSWORD RESET
	url(r'^password_reset/$', auth_views.password_reset, {
		'template_name'			  : 'reset/password_reset_form.html',
		'subject_template_name'	  : 'email/password_reset_subject.txt',
		'html_email_template_name': 'email/password_reset_email.html',
		'from_email'			  : 'info@victory.genki.dk'
		}, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done,{'template_name': 'reset/password_reset_done.html'}, name='password_reset_done'),
	url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm,{'template_name': 'reset/password_reset_confirm.html'}, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete,{'template_name': 'reset/password_reset_complete.html'}, name='password_reset_complete'),
]

victory/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^', include('staff.urls')),
	url(r'^admin/', admin.site.urls),
]

staff/models.py
from django.db import models

from django.contrib.auth.models import User
from django.core.validators import RegexValidator, MinValueValidator, MaxValueValidator
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.

class Team(models.Model):
	name = models.CharField(max_length=50)
	logo = models.ImageField(upload_to='teams/avatars', default='static/img/userpreload.png')
	background = models.ImageField(upload_to='teams/backgrounds', default='static/img/userpreload.png')
	description = models.TextField(blank=True)
	people_needed = models.PositiveSmallIntegerField()
	members = models.ManyToManyField(User, through='TeamMembership')
	accepts_applications = models.BooleanField()

	@property
	def teamleaders_listable(self):
		leaders = self.members.filter(teammembership__leader=True)
		return ", ".join(l.extendeduser.nickname for l in leaders)

	@property
	def multiple_teamleaders(self):
		if len(self.members.filter(teammembership__leader=True)) > 1:
			return True
		else:
			return False

	def __str__(self):
		return self.name

class TeamMembership(models.Model):
	user = models.ForeignKey(User)
	team = models.ForeignKey(Team)
	leader = models.BooleanField(default=False)
	groupleader = models.BooleanField(default=False)

class DriversLicenceCategories(models.Model): # No plural
	category = models.CharField(max_length=3)

	def __str__(self):
		return self.category

class Language(models.Model):
	name = models.CharField(max_length=16)

	def __str__(self):
		return self.name

class TShirt(models.Model):
	description = models.CharField(max_length=32)

class Sock(models.Model):
	description = models.CharField(max_length=32)

class ExtendedUser(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	nickname = models.CharField(max_length=20)
	birthdate = models.DateField(null=True, blank=True)
	postal_code = models.CharField(max_length=10)
	phone_number_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+4570131415'. Up to 15 digits allowed.")
	phone_number = models.CharField(max_length=16, validators=[phone_number_regex], blank=True)
	phone_number_show = models.BooleanField(default=False)
	emergency_number = models.CharField(max_length=16, validators=[phone_number_regex], blank=True)
	drivers_licence = models.ManyToManyField(DriversLicenceCategories, blank=True)
	avatar = models.ImageField(upload_to='users/avatars', default='static/img/userpreload.png')
	background = models.ImageField(upload_to='users/backgrounds', default='static/img/userpreload.png')
	team = models.ForeignKey(Team, null=True, blank=True)
	languages = models.ManyToManyField(Language, blank=True)
	tshirt = models.ForeignKey(TShirt, null=True, blank=True)
	sock = models.ForeignKey(Sock, null=True, blank=True)
	facebook_link = models.URLField(max_length=200, blank=True, null=True)
	twitter_link = models.URLField(max_length=200, blank=True, null=True)
	soundcloud_link = models.URLField(max_length=200, blank=True, null=True)
	youtube_link = models.URLField(max_length=200, blank=True, null=True)
	child_record = models.DateField(null=True, blank=True)
	special_considerations = models.TextField(blank=True)

@receiver(post_save, sender=User)
def update_user_extendeduser(sender, instance, created, **kwargs):
    if created:
        ExtendedUser.objects.create(user=instance)
    instance.extendeduser.save()

class Article(models.Model):
	author = models.ForeignKey(User)
	title = models.CharField(max_length=64)
	created = models.DateTimeField(null=True)
	body = models.TextField()

	def __str__(self):
		return self.title

class Alert(models.Model):
	title = models.CharField(max_length=32)
	body = models.TextField(blank=True)
	start = models.DateTimeField()
	end = models.DateTimeField()

class UnauthenticatedSession(models.Model):
	user = models.ForeignKey(User)
	token = models.CharField(max_length=36)
	otp = models.CharField(max_length=4)
	created = models.DateTimeField(auto_now_add=True)
	guesses_left = models.PositiveSmallIntegerField(default=3)
	successful = models.BooleanField(default=False)

	def __str__(self):
		return self.user.username

class TeamApplication(models.Model):
	from_user = models.ForeignKey(User)
	send = models.DateTimeField(auto_now=False, auto_now_add=True)
	to_team = models.ManyToManyField(Team)
	application_text = models.TextField()
	accepted = models.BooleanField(default=False)
	need_user_accept = models.BooleanField(default=False)
	need_info = models.BooleanField(default=False)
	need_info_comment = models.TextField(blank=True)
	refused = models.BooleanField(default=False)
	refused_comment = models.TextField(blank=True)

class EmailAndSmsMessages(models.Model):
	token = models.CharField(max_length=36)
	msgtype = models.CharField(max_length=36)
	team = models.ForeignKey(Team)
	members = models.ManyToManyField(TeamMembership)
	subject = models.CharField(max_length=50)
	message =  models.TextField(blank=True)

staff/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import TeamApplication, Team, TeamMembership, TShirt, DriversLicenceCategories, Language
from django.forms import ModelChoiceField, ModelMultipleChoiceField

class SignUpForm(UserCreationForm):
	postal_code = forms.CharField(max_length=10, required=True)
	phone_number = forms.CharField(max_length=16, required=True)

	class Meta:
		model = User
		fields = ('username', 'first_name', 'last_name', 'email', 'postal_code', 'phone_number', 'password1', 'password2', )

	def clean(self):
		cleaned_data = super(SignUpForm, self).clean()
		username = cleaned_data.get('username')
		if username and User.objects.filter(username__iexact=username).exists():
			self.add_error('username', 'A user with that username already exists.')
		return cleaned_data

class TshirtChoiceField(ModelChoiceField):
    def label_from_instance(self, obj):
        return obj.description

class DriversLicenceCategoriesMultipleChoiceField(ModelMultipleChoiceField):
    def label_from_instance(self, obj):
        return obj.category

class LanguageMultipleChoiceField(ModelMultipleChoiceField):
    def label_from_instance(self, obj):
        return obj.name

class UpdateProfileForm(forms.ModelForm):
	birthdate = forms.DateField(input_formats=['%d-%m-%Y'],required=False)
	phone_number = forms.CharField(max_length=16, required=True)
	phone_number_show = forms.BooleanField(required=False)
	emergency_number = forms.CharField(max_length=16, required=False)
	postal_code = forms.CharField(max_length=10, required=True)
	languages = LanguageMultipleChoiceField(queryset=Language.objects.all(),required=False)
	drivers_licence = DriversLicenceCategoriesMultipleChoiceField(queryset=DriversLicenceCategories.objects.all(),required=False)
	tshirt = TshirtChoiceField(queryset=TShirt.objects.all(),required=False)
	special_considerations = forms.CharField(required=False)
	class Meta:
		model = User
		fields = ('username', 'first_name', 'last_name', 'email', 'birthdate', 'phone_number', 'phone_number_show', 'emergency_number', 'postal_code', 'languages', 'drivers_licence', 'tshirt', 'special_considerations',)

class UpdateSociallinksForm(forms.ModelForm):
	facebook_link = forms.URLField(max_length=200, required=False)
	twitter_link = forms.URLField(max_length=200, required=False)
	soundcloud_link = forms.URLField(max_length=200, required=False)
	youtube_link = forms.URLField(max_length=200, required=False)
	class Meta:
		model = User
		fields = ('facebook_link','twitter_link','soundcloud_link','youtube_link', )

class UpdateProfileAvatar(forms.ModelForm):
	avatar = forms.ImageField()
	class Meta:
		model = User
		fields = ('avatar',)

class UpdateProfileBackground(forms.ModelForm):
	background = forms.ImageField()
	class Meta:
		model = User
		fields = ('background',)

class SendApplication(forms.ModelForm):
	class Meta:
		model = TeamApplication
		fields = ('from_user', 'to_team', 'application_text',)

class FeedbackSupportForm(forms.Form):
	first_name = forms.CharField(max_length=30, required=True)
	last_name = forms.CharField(max_length=30, required=True)
	email = forms.EmailField(required=True)
	message = forms.CharField(widget=forms.Textarea, required=True)

	class Meta:
		fields = ('username', 'first_name', 'last_name', 'email', 'message',)

class TeamSettings_GeneralForm(forms.ModelForm):
	class Meta:
		model = Team
		fields = ('name', 'accepts_applications',)

class UpdateTeamlogo(forms.ModelForm):
	logo = forms.ImageField()
	class Meta:
		model = Team
		fields = ('logo',)

class UpdateTeambackground(forms.ModelForm):
	background = forms.ImageField()
	class Meta:
		model = Team
		fields = ('background',)

class TeamSettings_DescriptionForm(forms.ModelForm):
	class Meta:
		model = Team
		fields = ('description',)

class TeamSettings_acceptForm(forms.ModelForm):
	class Meta:
		model = TeamMembership
		fields = ('user',)

class TeamSettings_needinfo_andrefuseForm(forms.Form):
	user = forms.IntegerField()
	comment = forms.CharField(widget=forms.Textarea, required=False)
	class Meta:
		fields = ('user', 'comment',)

class TeamSettings_AddForm(forms.ModelForm):
	class Meta:
		model = TeamMembership
		fields = ('user','team', 'leader')

staff/templates/team/add_member.html
{% extends "base.html" %}

{% load static %}

{% block title %}
Team Settings - Chaos, Genki
{% endblock %}

{% block header %}
<link rel="stylesheet" href="{% static 'css/application.css' %}">
{% endblock %}

{% block content %}
<section role="content">
	<div class="container">
		<h1 class="line-top">Add Member to {{ requested_team.name }}.</h1>
		<a href="{% url 'teamsettings_message' requested_team.pk %}" class="vicbtn vicbtn-blue vicbtn-bottom"><i class="fa fa-envelope" aria-hidden="true"></i> Send message</a>
		{% if messages %}
		<div class="alert alert-success" role="alert">
			{% for message in messages %}
			<p>{{ message }}</p>
			{% endfor %}
		</div>
		{% endif %}
		<ul class="nav nav-tabs" id="teamstab" role="tablist">
			<li class="nav-item">
				<a class="vic-tablink" id="team-settings" href="{% url 'teamsettings_general' requested_team.pk %}">General</a>
			</li>
			<li class="nav-item">
				<a class="vic-tablink " id="team-description" href="{% url 'teamsettings_description' requested_team.pk %}">Description</a>
			</li>
			<li class="nav-item">
				<a class="vic-tablink active" id="team-members" href="{% url 'teamsettings_members' requested_team.pk %}">Members</a>
			</li>
			<li class="nav-item">
				<a class="vic-tablink" id="team-applications"  href="{% url 'teamsettings_applications' requested_team.pk %}">Applications</a>
			</li>
		</ul>

		<div class="row">
			<div class="col">
				<form action="{% url 'teamsettings_members_add' requested_team.pk %}" method="POST">
					{% csrf_token %}
					<div class="custompanel no-m-bottom">
						<p>If you get an error 500 when adding an user, its most likely because the user is on a team already.<br>
							Also we will implement an code generator for you to just give a code out to a person to enter it they will automaticly join your team.
						</p>
						<hr style="border-color:rgba(0, 0, 0, 0.23);">
						<div class="form-group">
							<label>Select user to add.</label>
							<select id="users" name="user" class="users form-control">
								{% for usere in users %}
								<option value="{{usere.id}}">{{usere.first_name}} "{{usere.extendeduser.nickname}}" {{usere.last_name}}</option>
								{% endfor %}
							</select>
						</div>
						<div class="form-check">
							<label class="form-check-label">
								<input id="id_leader" name="leader" type="checkbox" class="form-check-input">
								Make Leader?
							</label>
						</div>
						<input type="hidden" id="id-team" name="team" value="{{ requested_team.pk }}">
					</div>
					<button type="submit" class="vicbtn vicbtn-green w-100">Add Member</button>
				</form>
			</div>
		</div>
	</div>
</section>
{% endblock %}

{% block scripts %}
<script src="{% static 'js/application.js' %}"></script>
<script type="text/javascript">
  $('.users').select2();
</script>
{% endblock %}

staff/templates/team/applications.html
{% extends "base.html" %}

{% load static %}

{% block title %}
Team Settings - Chaos, Genki
{% endblock %}

{% block content %}
<section role="content">
	<div class="container">
		<h1 class="line-top">Team Applications for {{ requested_team.name }}.</h1>
		<a href="{% url 'teamsettings_message' requested_team.pk %}" class="vicbtn vicbtn-blue vicbtn-bottom"><i class="fa fa-envelope" aria-hidden="true"></i> Send message</a>
		{% if messages %}
		<div class="alert alert-success" role="alert">
			{% for message in messages %}
			<p>{{ message }}</p>
			{% endfor %}
		</div>
		{% endif %}
		<ul class="nav nav-tabs" id="teamstab" role="tablist">
			<li class="nav-item">
				<a class="vic-tablink" id="team-settings" href="{% url 'teamsettings_general' requested_team.pk %}">General</a>
			</li>
			<li class="nav-item">
				<a class="vic-tablink" id="team-description" href="{% url 'teamsettings_description' requested_team.pk %}">Description</a>
			</li>
			<li class="nav-item">
				<a class="vic-tablink" id="team-members" href="{% url 'teamsettings_members' requested_team.pk %}">Members</a>
			</li>
			<li class="nav-item">
				<a class="vic-tablink active" id="team-applications"  href="{% url 'teamsettings_applications' requested_team.pk %}">Applications</a>
			</li>
		</ul>
		<div class="custompanel">
			<p>All non-accepted applications are here.<br>
				If u accept an user to the team the user will recieve an email and an SMS with they has been accepted into the team! If a user tho has applied to more than one team, they'd have to logon to confirm the team they wanna join.<br>
			With that said all applications that are accepted you can find <a href="#"><u>By clicking me.(Coming soon.)</u></a></p>
			<hr style="border-color:rgba(0, 0, 0, 0.23);">
		</div>

		{% for apply in applications %}
		{% if apply.accepted or apply.need_info or apply.refused or apply.need_user_accept %}
		{% else %}
		<div class="team bg-shadow">
			<div class="bgbox bgbox--browse">
				<div class="banner banner--scaled">
					<div class="application-shade"></div>
				</div>
				<div class="details-box applicationboxheader clearfix">
					<img class="artwork" src="{{ apply.from_user.extendeduser.avatar.url }}">
					<a href="{% url 'user' apply.from_user.pk %}" target="_blank"><h3>{{ apply.from_user.first_name }} "{{ apply.from_user.extendeduser.nickname }}" {{ apply.from_user.last_name }} <i class="fa fa-external-link" aria-hidden="true"></i></h3></a>
					<p><b>Sent:</b> {{ apply.send|date:"F j, Y, H:i"}}</p>
					<p><b>BirthYear:</b> {{ apply.from_user.extendeduser.birthdate|date:"Y"}}
					<p><b>Language:</b> {% for lang in apply.from_user.extendeduser.languages.all %}<span class="application-lang">{{lang.name}}</span>{% endfor %}</p>
					<p><b>Special cons:</b> {% if apply.from_user.extendeduser.special_considerations %}{{apply.from_user.extendeduser.special_considerations}}{%else%}Nothing specified{% endif %}</p>
				</div>
				<div class="application-text w100">
					{{ apply.application_text|linebreaksbr }}
				</div>
				<div class="application-actions">
					<form style="margin-right:2px;" action="{% url 'teamsettings_accept_applications' requested_team.pk %}" method="post">
						{% csrf_token %}
						<input type="hidden" id="id-user" name="user" value="{{apply.from_user.pk}}">
						<button type="submit" class="vicbtn vicbtn-green full-width"><i class="fa fa-check" aria-hidden="true"></i> Accept</button>
					</form>
					<form style="margin-right:2px;" action="{% url 'teamsettings_needinfo_applications' requested_team.pk %}" method="post">
						{% csrf_token %}
						<input type="hidden" id="id-user" name="user" value="{{apply.from_user.pk}}">
						<button type="submit" class="vicbtn vicbtn-yellow full-width"><i class="fa fa-question" aria-hidden="true"></i> Need info</button>
						<textarea rows="2" class="victext-input vic-block" id="id_comment" name="comment" placeholder="Write a comment here"></textarea>
					</form>
					<form style="margin-right:2px;" action="{% url 'teamsettings_refuse_applications' requested_team.pk %}" method="post">
						{% csrf_token %}
						<input type="hidden" id="id-user" name="user" value="{{apply.from_user.pk}}">
						<button type="submit" class="vicbtn vicbtn-red full-width"><i class="fa fa-times" aria-hidden="true"></i> Refuse</button>
						<textarea rows="2" class="victext-input vic-block" id="id_comment" name="comment" placeholder="Write a comment here"></textarea>
					</form>
				</div>
			</div>
		</div>
		{% endif %}
		{% endfor %}
	</div>
</section>
{% endblock %}

staff/templates/team/description.html
{% extends "base.html" %}

{% load static %}

{% block title %}
Team Settings - Chaos, Genki
{% endblock %}

{% block content %}
<section role="content">
	<div class="container">
		<h1 class="line-top">Team Description for {{ requested_team.name }}.</h1>
		<a href="{% url 'teamsettings_message' requested_team.pk %}" class="vicbtn vicbtn-blue vicbtn-bottom"><i class="fa fa-envelope" aria-hidden="true"></i> Send message</a>
		{% if messages %}
		<div class="alert alert-success" role="alert">
			{% for message in messages %}
			<p>{{ message }}</p>
			{% endfor %}
		</div>
		{% endif %}
		<ul class="nav nav-tabs" id="teamstab" role="tablist">
			<li class="nav-item">
				<a class="vic-tablink" id="team-settings" href="{% url 'teamsettings_general' requested_team.pk %}">General</a>
			</li>
			<li class="nav-item">
				<a class="vic-tablink active" id="team-description" href="{% url 'teamsettings_description' requested_team.pk %}">Description</a>
			</li>
			<li class="nav-item">
				<a class="vic-tablink" id="team-members" href="{% url 'teamsettings_members' requested_team.pk %}">Members</a>
			</li>
			<li class="nav-item">
				<a class="vic-tablink" id="team-applications"  href="{% url 'teamsettings_applications' requested_team.pk %}">Applications</a>
			</li>
		</ul>
		<div class="row">
			<div class="col">
				<form action="" method="POST">
					{% csrf_token %}
					<div class="custompanel no-m-bottom">
						<p>Everything with a * is required</p>
						<p>You can use basic html for headings and stuff more info will be coming up.</p>
						<hr style="border-color:rgba(0, 0, 0, 0.23);">
						<div class="form-group">
							<label style="margin-top:15px;" for="description">Write your Team description here</label>
							<textarea class="victext-input vic-block full-width" id="id_description" name="description" rows="6">{{ requested_team.description }}</textarea>
						</div>
					</div>
					<button type="submit" class="vicbtn vicbtn-green w-100">Save</button>
				</form>
			</div>
		</div>
	</div>
</section>
{% endblock %}

staff/templates/team/settings.html
{% extends "base.html" %}

{% load static %}

{% block title %}
Team Settings - Chaos, Genki
{% endblock %}

{% block content %}
<section role="content">
	<div class="container">
		<h1 class="line-top">Team Settings for {{ requested_team.name }}.</h1>
		<a href="{% url 'teamsettings_message' requested_team.pk %}" class="vicbtn vicbtn-blue vicbtn-bottom"><i class="fa fa-envelope" aria-hidden="true"></i> Send message</a>
		{% if messages %}
		<div class="alert alert-success" role="alert">
			{% for message in messages %}
			<p>{{ message }}</p>
			{% endfor %}
		</div>
		{% endif %}
		<ul class="nav nav-tabs" id="teamstab" role="tablist">
			<li class="nav-item">
				<a class="vic-tablink active" id="team-settings" href="{% url 'teamsettings_general' requested_team.pk %}">General</a>
			</li>
			<li class="nav-item">
				<a class="vic-tablink" id="team-description"  href="{% url 'teamsettings_description' requested_team.pk %}">Description</a>
			</li>
			<li class="nav-item">
				<a class="vic-tablink" id="team-members" href="{% url 'teamsettings_members' requested_team.pk %}">Members</a>
			</li>
			<li class="nav-item">
				<a class="vic-tablink" id="team-applications"  href="{% url 'teamsettings_applications' requested_team.pk %}">Applications</a>
			</li>
		</ul>
		<div class="row">
			<div class="col">
				<form action="" method="POST">
					{% csrf_token %}
					<div class="custompanel no-m-bottom">
						<h3>Settings</h3>
						<hr style="border-color:rgba(0, 0, 0, 1);">
						<div class="form-group">
							<label class="viclabelline-bottom" for="id_name">Team Name</label>
							<input type="text" class="victext-input vic-block full-width" name="name" maxlength="40" required id="id_name" value="{{ requested_team.name }}">
						</div>
						<div class="form-check">
							<label class="form-check-label">
								<input id="id_accepts_applications" {% if requested_team.accepts_applications %} checked {% endif %} name="accepts_applications" type="checkbox" class="form-check-input">
								Is the team accepting applications?
							</label>
						</div>
					</div>
					<button type="submit" class="vicbtn vicbtn-green w-100">Save</button>
				</form>
			</div>
			<div class="col">
				<form action="{% url 'teamsettings_logo' requested_team.pk %}" method="POST" enctype="multipart/form-data">
					{% csrf_token %}
					<div class="custompanel no-m-bottom">
						<h3>Logo</h3>
						<hr style="border-color:rgba(0, 0, 0, 1);">
						<div class="form-group">
							<div class="setting-user-avatar">
								<img class="user-avatar" src="{{ requested_team.logo.url }}">
							</div>
							<label for="id_logo">Change Team logo image.</label>
							<input id="id_logo" style="color: #000;" class="victext-input vic-block full-width" type="file" name="logo"></input>
							<small id="id_logoHelpBlock" class="form-text text-muted">
								 Current: <a href="{{ requested_team.logo.url }}">{{ requested_team.logo.url }}</a>
							</small>
						</div>
					</div>
					<button type="submit" class="vicbtn vicbtn-green w-100">Save</button>
				</form>
				<form action="{% url 'teamsettings_background' requested_team.pk %}" method="POST" enctype="multipart/form-data">
					{% csrf_token %}
					<div class="custompanel no-m-bottom">
						<h3>Background</h3>
						<hr style="border-color:rgba(0, 0, 0, 1);">
						<div class="form-group">
							<div class="setting-user-avatar">
								<img class="user-avatar" src="{{ requested_team.background.url }}">
							</div>
							<label for="id_background">Cover</label>
							<input id="id_background" style="color: #000;" class="victext-input vic-block full-width" type="file" name="background"></input>
							<small id="id_backgroundHelpblock" class="form-text text-muted">
								 Current: <a href="{{ requested_team.background.url }}">{{ requested_team.background.url }}</a>
							</small>
						</div>
					</div>
					<button type="submit" class="vicbtn vicbtn-green w-100">Save</button>
				</form>
			</div>
		</div>
	</div>
</section>
{% endblock %}